### ISSUE TITLE
Unica 6 Custom ( mateba_j_custom), leupold scop, tritium glow bleed through

### ISSUE THREAD

**Issue by Hoshizoku** [andtheherois/3DSS-for-ATHI-Weapon-Pack#1]
Unica 6 Custom ( mateba_j_custom) the leupold scope, tritium glow bleed through.

![grafik](https://github.com/andtheherois/3DSS-for-ATHI-Weapon-Pack/assets/174358400/18fc9bb4-c6a1-432f-a710-17e3e0b76934)

**Comment by andtheherois** [comment]
this was fixed in the last update
